# Generated by Django 4.1.7 on 2023-03-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nike',
            old_name='prise',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='nike',
            name='ddescription',
        ),
        migrations.AddField(
            model_name='nike',
            name='description',
            field=models.TextField(default=1, verbose_name='описания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='nike',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='категория '),
        ),
    ]
