# Generated by Django 4.1.7 on 2023-03-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_prise_nike_price_remove_nike_ddescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nike',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='nike',
            old_name='image',
            new_name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sneakers_images', verbose_name='изображение')),
                ('sneakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nike')),
            ],
        ),
    ]
